<?php

$catalog_generator_default_option = [
    "types_product" => '1000',
    "types_price" => '10',
    "types_store" => '100',
    "types_productproperty" => '100',
    "types_skuproperty" => '200',
    "sku_count" => '10',
    "words_in_el_name" => '5',
    "preview_text_length" => '150',
    "detail_text_length" => '600',
    "preview_picture_width" => '300',
    "preview_picture_height" => '200',
    "detail_picture_width" => '800',
    "detail_picture_height" => '600',
    "catalog_price_max_decimals" => '2',
    "catalog_price_min" => '0',
    "catalog_price_max" => '10000',
    "catalog_weight_min" => '0',
    "catalog_weight_max" => '100',
    "catalog_width_min" => '0',
    "catalog_width_max" => '100',
    "catalog_length_min" => '0',
    "catalog_length_max" => '100',
    "catalog_height_min" => '0',
    "catalog_height_max" => '100',
    "catalog_quantity_min" => '0',
    "catalog_quantity_max" => '100',
    "property_multiple_count" => '3',
    "property_string_length" => '10',
    "property_text_length" => '600',
];