CREATE TABLE `catalog_generator` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `STEP` INT(11) DEFAULT 0,
    `STATUS` INT(11) DEFAULT 0,
    `TYPE` VARCHAR(65536) NOT NULL,
    `ITEMS_PER_STEP` INT(11) DEFAULT 1,
    `CREATED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(ID)
);